import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Header/Header";
import CustomReduxProvider from "@/redux/provider";
import { AxiosInterceptor } from "@/utils/AxiosFetch";
import PageLoader from "@/components/PageLoader/PageLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <CustomReduxProvider>
                    <AxiosInterceptor>
                        <PageLoader />
                        <Header />
                        {children}
                    </AxiosInterceptor>
                </CustomReduxProvider>
            </body>
        </html>
    );
}
